dist: xenial
language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
script: pipenv run pyinstaller jarvis.spec
addons:
  apt:
    packages:
      python3-setuptools
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "dist/jarvis"
  skip_cleanup: true
  on:
    tags: true
